import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/Components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { IfHorizontalProvider } from "./ArchDia/constants/ifHorizontal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <IfHorizontalProvider> {/* Wrap your layout with IfHorizontalProvider */}
          <Navbar />
          <ToastContainer />
          <main className="flex-grow mt-16">{children}</main>
        </IfHorizontalProvider>
      </body>
    </html>
  );
}

