export const initialEdges = [
  {
    id: "e1-2",
    source: "1",
    target: "2",

    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  {
    id: "e3-4",
    source: "3",
    target: "4",
    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",

    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  {
    id: "e3-6",
    source: "3",
    target: "6",

    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  {
    id: "e6-7",
    label: "Compute Nodes",
    source: "6",
    target: "7",
    targetHandle: "top",
    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
  // {
  //   id: "e7-8",
  //   label: "Compute Nodes",
  //   source: "7",
  //   target: "8",
  //   targetHandle: "top",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "black", strokeWidth: 2 },
  // },
  // {
  //   id: "e8-9",
  //   label: "Compute Nodes",
  //   source: "8",
  //   target: "9",
  //   targetHandle: "top",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "black", strokeWidth: 2 },
  // },
  // {
  //   id: "e9-10",
  //   label: "Compute Nodes",
  //   source: "9",
  //   target: "10",
  //   targetHandle: "top",
  //   arrowHeadType: "arrowclosed",
  //   style: { stroke: "black", strokeWidth: 2 },
  // },
  {
    id: "e7-11",
    source: "7",
    sourceHandle: "bottom",
    target: "11",
    targetHandle: "top",

    arrowHeadType: "arrowclosed",
    style: { stroke: "black", strokeWidth: 2 },
  },
];
